### PR TITLE
Containerize application with docker

### PR DESCRIPTION
**Pull request by ctmbl**
I added a Dockerfile to run the app inside it instead of running it on the host system (because right now it runs on the iscsc server as a process of `gregory` I'd prefer see it in `docker ps` you know).
I also added a `run.sh` script to easily run it!
I updated the README.md

**EDIT**: heavily inspired from [Solwerzs root-me bot](https://github.com/Slowerzs/RootMeBotV2/blob/main/Dockerfile)

### CODE REVIEW

**Comment by gbrivady** [comment]
No clue how docker works, to I will let @amtoine (or anyone else that knows better) check this PR

**Comment by ctmbl** [comment]
@gbrivady you can simply test it if you want!
Also see my edit above :wink:

**Review by amtoine — COMMENTED** [review]
the changes look ok :+1: 

did you run it already?

**Comment by ctmbl** [comment]
@amtoine yep I tested it locally seems to work perfectly! Tks to it I also detected the messing requriements that lead to #2

**Comment by amtoine** [comment]
> @amtoine yep I tested it locally seems to work perfectly! Tks to it I also detected the messing requriements that lead to #2
>
cool :ok_hand:

**Review by amtoine — APPROVED** [review]

**Pull request merged**
